##\
# This file is a part of the phpMussel\CLI package.
# Homepage: https://phpmussel.github.io/
#
# PHPMUSSEL COPYRIGHT 2013 AND BEYOND BY THE PHPMUSSEL TEAM.
#
# License: GNU/GPLv2
# @see LICENSE.txt
#
# This file: Configuration defaults file (last modified: 2020.07.03).
##/

cli:
 allow_process_forking:
  type: "bool"
  default: true
